import supabase from "../supabase"
import { toDateOnly } from "../../libs/datelib"
import { roundCurrency } from "../../libs/money"
import { encryptField, decryptField } from "../crypto"

type ReceivableRow = {
    id: number
    occurred_at: string
    notes: string | null
    total_amount: number
    own_share: number
    receivable_amount: number
    settled_amount: number
    created_at: string
    expense_id: number | null
}

export type ReceivableInput = {
    occurredAt: Date
    notes: string
    totalAmount: number
    ownShare: number
    expenseId?: number | null
}

const RECEIVABLE_SELECT = [
    "id", "occurred_at", "notes", "total_amount", "own_share", "receivable_amount", "settled_amount", "created_at", "expense_id",
].join(", ")

/** A receivable is fully recovered once settled_amount reaches receivable_amount (rounding-safe). */
function statusOf(receivableAmount: number, settledAmount: number): "pending" | "partial" | "settled" {
    if (settledAmount <= 0) return "pending"
    return settledAmount >= receivableAmount - 0.005 ? "settled" : "partial"
}

function toReceivable(row: ReceivableRow) {
    return {
        id: row.id,
        date: row.occurred_at,
        notes: decryptField(row.notes),
        totalAmount: row.total_amount,
        ownShare: row.own_share,
        receivableAmount: row.receivable_amount,
        settledAmount: row.settled_amount,
        status: statusOf(row.receivable_amount, row.settled_amount),
        createdAt: row.created_at,
        expenseId: row.expense_id,
    }
}

/**
 * Lists a user's shared-expense receivables (money fronted for a group,
 * still owed back), most recent first.
 */
async function getReceivablesByUserId(user_id: string) {
    const {data, error} = await supabase.from("shared_expense_receivables")
        .select(RECEIVABLE_SELECT)
        .eq("user_id", user_id)
        .order("occurred_at", {ascending: false})
    if (error) console.error("sharedExpenses.getReceivablesByUserId: failed to read receivables", error)
    if (error || !data) return []
    return (data as unknown as ReceivableRow[]).map(toReceivable)
}

/**
 * Records a new receivable. own_share is informational only here (the real
 * outflow with amount = ownShare is inserted separately via transactions.insertNew);
 * receivable_amount = totalAmount - ownShare is what's actually owed back.
 */
async function insertReceivable(user_id: string, input: ReceivableInput) {
    const receivableAmount = roundCurrency(input.totalAmount - input.ownShare)
    if (receivableAmount <= 0) return null

    const {data, error} = await supabase.from("shared_expense_receivables").insert({
        user_id,
        occurred_at: toDateOnly(input.occurredAt),
        notes: encryptField(input.notes),
        total_amount: roundCurrency(input.totalAmount),
        own_share: roundCurrency(input.ownShare),
        receivable_amount: receivableAmount,
        expense_id: input.expenseId ?? null,
    }).select(RECEIVABLE_SELECT).single()
    if (error) console.error("sharedExpenses.insertReceivable: failed to insert receivable", error)
    if (error || !data) return null
    return toReceivable(data as unknown as ReceivableRow)
}

export type ImportedSharedExpenseLink = {
    expenseId: number
    occurredAt: Date
    notes: string
    totalAmount: number
    ownShare: number
}

export type ImportedReimbursementLink = {
    expenseId: number
    receivableId: number
    amount: number
}

/** Creates all receivables generated by an import in one write. */
async function insertImportedReceivables(user_id: string, links: ImportedSharedExpenseLink[]) {
    if (links.length === 0) return []
    const rows = links.map((link) => ({
        user_id,
        occurred_at: toDateOnly(link.occurredAt),
        notes: encryptField(link.notes),
        total_amount: roundCurrency(link.totalAmount),
        own_share: roundCurrency(link.ownShare),
        receivable_amount: roundCurrency(link.totalAmount - link.ownShare),
        expense_id: link.expenseId,
    }))
    if (rows.some((row) => row.receivable_amount <= 0)) return null
    const {data, error} = await supabase.from("shared_expense_receivables")
        .insert(rows).select(RECEIVABLE_SELECT)
    if (error) console.error("sharedExpenses.insertImportedReceivables: failed", error)
    if (error || !data) return null
    return (data as unknown as ReceivableRow[]).map(toReceivable)
}

/** Links imported income movements to receivables and refreshes their settled totals. */
async function insertImportedReimbursements(user_id: string, links: ImportedReimbursementLink[]) {
    if (links.length === 0) return []
    const rows = links.map((link) => ({
        user_id,
        receivable_id: link.receivableId,
        expense_id: link.expenseId,
        amount: roundCurrency(link.amount),
    }))
    const {data, error} = await supabase.from("shared_expense_reimbursements")
        .insert(rows).select("id, receivable_id, expense_id, amount")
    if (error) console.error("sharedExpenses.insertImportedReimbursements: failed", error)
    if (error || !data) return null

    const affected = Array.from(new Set(links.map((link) => link.receivableId)))
    for (const receivableId of affected) {
        const {data: payments, error: sumError} = await supabase.from("shared_expense_reimbursements")
            .select("amount").eq("user_id", user_id).eq("receivable_id", receivableId)
        if (sumError || !payments) return null
        const settled = roundCurrency(payments.reduce((sum, payment) => sum + Number(payment.amount), 0))
        const {error: updateError} = await supabase.from("shared_expense_receivables")
            .update({settled_amount: settled}).eq("user_id", user_id).eq("id", receivableId)
        if (updateError) return null
    }
    return data
}

/**
 * Adds `amount` to a receivable's settled total (clamped so it never exceeds
 * receivable_amount), scoped to the owning user. Never touches expense/income
 * category totals — money coming back is a balance-only event, not income.
 */
async function settleReceivable(user_id: string, receivable_id: number, amount: number) {
    const {data: existing, error: readError} = await supabase.from("shared_expense_receivables")
        .select(RECEIVABLE_SELECT).eq("user_id", user_id).eq("id", receivable_id).maybeSingle()
    if (readError) console.error("sharedExpenses.settleReceivable: failed to read receivable", readError)
    if (readError || !existing) return null

    const row = existing as unknown as ReceivableRow
    const newSettled = Math.min(row.receivable_amount, roundCurrency(row.settled_amount + amount))

    const {data, error} = await supabase.from("shared_expense_receivables")
        .update({settled_amount: newSettled})
        .eq("user_id", user_id)
        .eq("id", receivable_id)
        .select(RECEIVABLE_SELECT)
        .single()
    if (error) console.error("sharedExpenses.settleReceivable: failed to update receivable", error)
    if (error || !data) return null
    return toReceivable(data as unknown as ReceivableRow)
}

/** Converts an already-recorded outflow into a shared expense. */
async function linkExistingExpense(user_id: string, expense_id: number, own_share: number, explicit_total?: number) {
    const {data: expense, error: expenseError} = await supabase.from("transactions")
        .select("id, occurred_at, notes, amount, cash_amount, is_expense")
        .eq("user_id", user_id).eq("id", expense_id).maybeSingle()
    if (expenseError || !expense || expense.is_expense !== true) return null
    const totalAmount = roundCurrency(explicit_total ?? Number(expense.cash_amount ?? expense.amount))
    const ownShare = roundCurrency(own_share)
    if (ownShare < 0 || ownShare >= totalAmount) return null

    const {data: existing, error: existingError} = await supabase.from("shared_expense_receivables")
        .select(RECEIVABLE_SELECT).eq("user_id", user_id).eq("expense_id", expense_id).maybeSingle()
    if (existingError) return null

    if (existing) {
        const previous = existing as unknown as ReceivableRow
        const receivableAmount = roundCurrency(totalAmount - ownShare)
        // Never allow an edit to make already-recorded reimbursements exceed
        // the newly calculated amount owed.
        if (receivableAmount < Number(previous.settled_amount) - 0.005) return null
        const {data: updated, error: updateReceivableError} = await supabase.from("shared_expense_receivables").update({
            total_amount: totalAmount,
            own_share: ownShare,
            receivable_amount: receivableAmount,
        }).eq("user_id", user_id).eq("id", previous.id).select(RECEIVABLE_SELECT).single()
        if (updateReceivableError || !updated) return null
        const {error: updateExpenseError} = await supabase.from("transactions").update({
            amount: ownShare,
            cash_amount: totalAmount,
        }).eq("user_id", user_id).eq("id", expense_id)
        if (updateExpenseError) {
            await supabase.from("shared_expense_receivables").update({
                total_amount: previous.total_amount,
                own_share: previous.own_share,
                receivable_amount: previous.receivable_amount,
            }).eq("user_id", user_id).eq("id", previous.id)
            return null
        }
        return toReceivable(updated as unknown as ReceivableRow)
    }

    const receivable = await insertReceivable(user_id, {
        occurredAt: new Date(String(expense.occurred_at)),
        notes: decryptField(expense.notes as string | null),
        totalAmount,
        ownShare,
        expenseId: expense_id,
    })
    if (!receivable) return null
    const {error: updateError} = await supabase.from("transactions").update({
        amount: ownShare,
        cash_amount: totalAmount,
    }).eq("user_id", user_id).eq("id", expense_id)
    if (updateError) {
        await deleteReceivable(user_id, receivable.id)
        return null
    }
    return receivable
}

/** Links an existing income movement to a receivable and excludes it from income statistics. */
async function linkExistingReimbursement(user_id: string, expense_id: number, receivable_id: number) {
    const {data: income, error: incomeError} = await supabase.from("transactions")
        .select("id, amount, is_expense").eq("user_id", user_id).eq("id", expense_id).maybeSingle()
    if (incomeError || !income || income.is_expense === true || Number(income.amount) <= 0) return null
    const {data: receivable, error: receivableError} = await supabase.from("shared_expense_receivables")
        .select("receivable_amount, settled_amount").eq("user_id", user_id).eq("id", receivable_id).maybeSingle()
    if (receivableError || !receivable) return null
    const amount = roundCurrency(Number(income.amount))
    const outstanding = roundCurrency(Number(receivable.receivable_amount) - Number(receivable.settled_amount))
    if (amount > outstanding + 0.005) return null

    const {error: updateError} = await supabase.from("transactions").update({exclude_from_statistics: true})
        .eq("user_id", user_id).eq("id", expense_id)
    if (updateError) return null
    const links = await insertImportedReimbursements(user_id, [{expenseId: expense_id, receivableId: receivable_id, amount}])
    if (!links) {
        await supabase.from("transactions").update({exclude_from_statistics: false}).eq("user_id", user_id).eq("id", expense_id)
        return null
    }
    return getReceivablesByUserId(user_id)
}

/**
 * Deletes a receivable owned by the user.
 */
async function deleteReceivable(user_id: string, receivable_id: number) {
    const {data: reimbursements, error: reimbursementError} = await supabase.from("shared_expense_reimbursements")
        .select("expense_id").eq("user_id", user_id).eq("receivable_id", receivable_id)
    if (reimbursementError) return null
    const {error, count} = await supabase.from("shared_expense_receivables")
        .delete({count: "exact"})
        .eq("user_id", user_id)
        .eq("id", receivable_id)
    if (error) console.error("sharedExpenses.deleteReceivable: failed to delete receivable", error)
    if (error) return null
    const reimbursementExpenseIds = (reimbursements || []).map((row) => Number(row.expense_id)).filter(Number.isFinite)
    if (reimbursementExpenseIds.length > 0) {
        const {error: restoreError} = await supabase.from("transactions").update({exclude_from_statistics: false})
            .eq("user_id", user_id).in("id", reimbursementExpenseIds)
        if (restoreError) return null
    }
    return {deletedCount: count ?? 0}
}

type ReimbursementRow = {
    id: number
    receivable_id: number
    expense_id: number
    amount: number
    created_at: string
}

/**
 * Lists a user's shared-expense reimbursement links (settlements tied to a
 * receivable), most recent first — used by the data-export endpoint.
 * getReceivablesByUserId already carries the aggregated settledAmount/status
 * a receivable needs for display; this is the raw per-settlement ledger.
 */
async function getReimbursementsByUserId(user_id: string) {
    const {data, error} = await supabase.from("shared_expense_reimbursements")
        .select("id, receivable_id, expense_id, amount, created_at")
        .eq("user_id", user_id)
        .order("created_at", {ascending: false})
    if (error) console.error("sharedExpenses.getReimbursementsByUserId: failed to read reimbursements", error)
    if (error || !data) return []
    return (data as unknown as ReimbursementRow[]).map((row) => ({
        id: row.id,
        receivableId: row.receivable_id,
        expenseId: row.expense_id,
        amount: row.amount,
        createdAt: row.created_at,
    }))
}

export default {
    getReceivablesByUserId,
    insertReceivable,
    settleReceivable,
    deleteReceivable,
    insertImportedReceivables,
    insertImportedReimbursements,
    linkExistingExpense,
    linkExistingReimbursement,
    getReimbursementsByUserId,
}
