#!/usr/bin/env node
/**
 * generateRoadmap.js — Generates src/data/roadmapData.js from:
 *   1. scripts/roadmap-items.json  (curated roadmap entries with bilingual titles)
 *   2. todo.md                     (auto-detects status from checkboxes & sections)
 *
 * Usage:
 *   node scripts/generateRoadmap.js
 *   npm run roadmap
 *
 * How it works:
 *   - Each item in roadmap-items.json has a `todoMatch` string.
 *   - The script searches todo.md for a line containing that string.
 *   - Status is inferred:
 *       • Line has [x] → 'completed'
 *       • Line has [ ] + item has forceStatus → uses forceStatus (e.g. 'in-progress')
 *       • Line has [ ] → 'planned'
 *       • No match found → keeps forceStatus or defaults to 'planned'
 *
 * To add a new roadmap item:
 *   1. Add the item to todo.md (if not already there)
 *   2. Add an entry to scripts/roadmap-items.json with a `todoMatch` string
 *   3. Run `npm run roadmap`
 *
 * To EXCLUDE a todo item from the roadmap:
 *   Simply don't add it to roadmap-items.json. Only items listed there appear.
 */

const { readFileSync, writeFileSync } = require('fs');
const { join } = require('path');

const ROOT = join(__dirname, '..');

// ── Read inputs ──
const todoContent = readFileSync(join(ROOT, 'todo.md'), 'utf-8');
const todoLines = todoContent.split('\n');
const roadmapItems = JSON.parse(
  readFileSync(join(ROOT, 'scripts', 'roadmap-items.json'), 'utf-8')
);

// ── Detect current section in todo.md ──
function getCurrentSection(line, currentSection) {
  if (/^## ✅/.test(line)) return 'completed';
  if (/^## 🔧/.test(line)) return 'todo';
  if (/^## 💡/.test(line)) return 'ideas';
  if (/^## .*Le Mie Idee/.test(line)) return 'personal';
  if (/^## .*Note Tecniche/.test(line)) return 'notes';
  return currentSection;
}

// ── Find matching line and infer status ──
function findStatus(todoMatch, forceStatus) {
  let section = '';

  for (const line of todoLines) {
    section = getCurrentSection(line, section);

    if (line.includes(todoMatch)) {
      const isChecked = /- \[x\]/.test(line) || /~~.*~~/.test(line);
      if (isChecked) return 'completed';
      if (forceStatus) return forceStatus;
      return 'planned';
    }
  }

  // No match found in todo.md
  if (forceStatus) return forceStatus;
  return 'planned';
}

// ── Generate roadmap data ──
const generated = roadmapItems.map((item) => {
  const status = findStatus(item.todoMatch, item.forceStatus);

  const entry = {
    id: item.id,
    title: item.title,
    description: item.description,
    status,
    category: item.category,
    icon: item.icon,
  };

  if (status === 'completed' && item.completedDate) {
    entry.completedDate = item.completedDate;
  }

  return entry;
});

// ── Sort: completed first, then in-progress, then planned ──
const statusOrder = { completed: 0, 'in-progress': 1, planned: 2 };
generated.sort((a, b) => statusOrder[a.status] - statusOrder[b.status]);

// ── Write output ──
const escapeQuotes = (s) => s.replace(/\\/g, '\\\\').replace(/'/g, "\\'");

let output = `/**
 * Roadmap Data — AUTO-GENERATED by scripts/generateRoadmap.js
 * DO NOT EDIT MANUALLY — edit scripts/roadmap-items.json instead.
 *
 * Status: 'completed' | 'in-progress' | 'planned'
 * Category: 'feature' | 'ux' | 'community' | 'security'
 *
 * Run: npm run roadmap
 */

const roadmapData = [\n`;

let currentStatus = '';
for (const item of generated) {
  if (item.status !== currentStatus) {
    const label = {
      completed: 'COMPLETED',
      'in-progress': 'IN PROGRESS',
      planned: 'PLANNED',
    }[item.status];
    output += `  /* ──────────── ${label} ──────────── */\n`;
    currentStatus = item.status;
  }

  output += `  {\n`;
  output += `    id: '${item.id}',\n`;
  output += `    title: { it: '${escapeQuotes(item.title.it)}', en: '${escapeQuotes(item.title.en)}' },\n`;
  output += `    description: {\n`;
  output += `      it: '${escapeQuotes(item.description.it)}',\n`;
  output += `      en: '${escapeQuotes(item.description.en)}'\n`;
  output += `    },\n`;
  output += `    status: '${item.status}',\n`;
  output += `    category: '${item.category}',\n`;
  output += `    icon: '${item.icon}',\n`;
  if (item.completedDate) {
    output += `    completedDate: '${item.completedDate}',\n`;
  }
  output += `  },\n`;
}

output += `];\n\n`;
output += `export default roadmapData;\n\n`;
output += `/**\n * Get items filtered by status\n */\n`;
output += `export const getItemsByStatus = (status) =>\n`;
output += `  roadmapData.filter((item) => item.status === status);\n\n`;
output += `/**\n * Get count of items per status\n */\n`;
output += `export const getStatusCounts = () => ({\n`;
output += `  completed: roadmapData.filter((i) => i.status === 'completed').length,\n`;
output += `  'in-progress': roadmapData.filter((i) => i.status === 'in-progress').length,\n`;
output += `  planned: roadmapData.filter((i) => i.status === 'planned').length,\n`;
output += `});\n`;

const outputPath = join(ROOT, 'src', 'data', 'roadmapData.js');
writeFileSync(outputPath, output, 'utf-8');

// ── Summary ──
const counts = { completed: 0, 'in-progress': 0, planned: 0 };
generated.forEach((i) => counts[i.status]++);

console.log('✅ roadmapData.js generated successfully!');
console.log(`   ${generated.length} items total: ${counts.completed} completed, ${counts['in-progress']} in-progress, ${counts.planned} planned`);
console.log(`   Output: ${outputPath}`);
