#!/usr/bin/env node
/**
 * generateRoadmap.js — Generates src/data/roadmapData.ts from:
 *   1. scripts/roadmap-items.json  (curated roadmap entries with bilingual titles)
 *   2. todo.md                     (auto-detects status from checkboxes)
 *
 * Usage:
 *   node scripts/generateRoadmap.js
 *   npm run roadmap
 *
 * How it works:
 *   - Preferred mapping uses stable marker IDs in todo lines:
 *       <!-- roadmap:<item-id> -->
 *   - Fallback mapping uses `todoMatch` text for backward compatibility.
 *   - Status is inferred:
 *       • Line has [x] → 'completed'
 *       • Line has [~] → 'in-progress'
 *       • Line has [ ] + item has forceStatus → uses forceStatus (e.g. 'in-progress')
 *       • Line has [ ] → 'planned'
 *       • No match found → keeps forceStatus or defaults to 'planned'
 *
 * To add a new roadmap item:
 *   1. Add the item to todo.md (if not already there)
 *   2. Add marker <!-- roadmap:<item-id> --> to that todo line
 *   3. Add an entry to scripts/roadmap-items.json (todoMatch optional as fallback)
 *   4. Run `npm run roadmap`
 *
 * To EXCLUDE a todo item from the roadmap:
 *   Simply don't add it to roadmap-items.json. Only items listed there appear.
 */

const { readFileSync, writeFileSync } = require('fs');
const { join } = require('path');

const ROOT = join(__dirname, '..');

// ── Read inputs ──
const todoContent = readFileSync(join(ROOT, 'todo.md'), 'utf-8');
const todoLines = todoContent.split('\n');
const roadmapItems = JSON.parse(
  readFileSync(join(ROOT, 'scripts', 'roadmap-items.json'), 'utf-8')
);

// ── Detect current section in todo.md ──
function getCurrentSection(line, currentSection) {
  if (/^## ✅/.test(line)) return 'completed';
  if (/^## 🔧/.test(line)) return 'todo';
  if (/^## 💡/.test(line)) return 'ideas';
  if (/^## .*Le Mie Idee/.test(line)) return 'personal';
  if (/^## .*Note Tecniche/.test(line)) return 'notes';
  return currentSection;
}

function escapeRegex(value) {
  return String(value).replace(/[.*+?^${}()|[\]\\]/g, '\\$&');
}

function isCompletedLine(line) {
  return /- \[x\]/i.test(line) || /~~.*~~/.test(line);
}

function isInProgressLine(line) {
  return /- \[~\]/i.test(line);
}

function getLineStatus(line, forceStatus) {
  if (isCompletedLine(line)) return 'completed';
  if (isInProgressLine(line)) return 'in-progress';
  if (forceStatus) return forceStatus;
  return 'planned';
}

function hasRoadmapMarker(line, itemId) {
  const markerRegex = new RegExp(`<!--\\s*roadmap\\s*:\\s*${escapeRegex(itemId)}\\s*-->`, 'i');
  return markerRegex.test(line);
}

// ── Find matching line and infer status ──
function findStatus(itemId, todoMatch, forceStatus) {
  let section = '';
  const normalizedMatch = String(todoMatch || '').toLowerCase();

  // 1) Preferred: stable marker ID
  for (const line of todoLines) {
    section = getCurrentSection(line, section);
    if (hasRoadmapMarker(line, itemId)) {
      return getLineStatus(line, forceStatus);
    }
  }

  // 2) Fallback: legacy text match
  for (const line of todoLines) {
    section = getCurrentSection(line, section);

    if (normalizedMatch && line.toLowerCase().includes(normalizedMatch)) {
      return getLineStatus(line, forceStatus);
    }
  }

  // No match found in todo.md
  if (forceStatus) return forceStatus;
  return 'planned';
}

// ── Generate roadmap data ──
const generated = roadmapItems.map((item) => {
  const status = findStatus(item.id, item.todoMatch, item.forceStatus);

  const entry = {
    id: item.id,
    title: item.title,
    description: item.description,
    status,
    category: item.category,
    icon: item.icon,
  };

  if (status === 'completed' && item.completedDate) {
    entry.completedDate = item.completedDate;
  }

  // Optional cross-link to a real GitHub issue (e.g. one that started life as
  // in-app feedback and got promoted to the roadmap) - most items omit this.
  if (item.githubIssue) {
    entry.githubIssue = item.githubIssue;
  }

  return entry;
});

// ── Sort: completed first, then in-progress, then planned ──
const statusOrder = { completed: 0, 'in-progress': 1, planned: 2 };
generated.sort((a, b) => statusOrder[a.status] - statusOrder[b.status]);

// ── Write output ──
const escapeQuotes = (s) => s.replace(/\\/g, '\\\\').replace(/'/g, "\\'");

let output = `/**
 * Roadmap Data — AUTO-GENERATED by scripts/generateRoadmap.js
 * DO NOT EDIT MANUALLY — edit scripts/roadmap-items.json instead.
 *
 * Run: npm run roadmap
 */

export type RoadmapStatus = 'completed' | 'in-progress' | 'planned';
export type RoadmapCategory = 'feature' | 'ux' | 'community' | 'security';

export interface RoadmapItem {
  id: string;
  title: { it: string; en: string };
  description: { it: string; en: string };
  status: RoadmapStatus;
  category: RoadmapCategory;
  icon: string;
  completedDate?: string;
  /** Real GitHub issue number, when one naturally exists for this item (see docs/FUTURE_DESIGNS.md). */
  githubIssue?: number;
}

const roadmapData: RoadmapItem[] = [\n`;

let currentStatus = '';
for (const item of generated) {
  if (item.status !== currentStatus) {
    const label = {
      completed: 'COMPLETED',
      'in-progress': 'IN PROGRESS',
      planned: 'PLANNED',
    }[item.status];
    output += `  /* ──────────── ${label} ──────────── */\n`;
    currentStatus = item.status;
  }

  output += `  {\n`;
  output += `    id: '${item.id}',\n`;
  output += `    title: { it: '${escapeQuotes(item.title.it)}', en: '${escapeQuotes(item.title.en)}' },\n`;
  output += `    description: {\n`;
  output += `      it: '${escapeQuotes(item.description.it)}',\n`;
  output += `      en: '${escapeQuotes(item.description.en)}'\n`;
  output += `    },\n`;
  output += `    status: '${item.status}',\n`;
  output += `    category: '${item.category}',\n`;
  output += `    icon: '${item.icon}',\n`;
  if (item.completedDate) {
    output += `    completedDate: '${item.completedDate}',\n`;
  }
  if (item.githubIssue) {
    output += `    githubIssue: ${Number(item.githubIssue)},\n`;
  }
  output += `  },\n`;
}

output += `];\n\n`;
output += `export default roadmapData;\n\n`;
output += `/**\n * Get items filtered by status\n */\n`;
output += `export const getItemsByStatus = (status: RoadmapStatus): RoadmapItem[] =>\n`;
output += `  roadmapData.filter((item) => item.status === status);\n\n`;
output += `/**\n * Get count of items per status\n */\n`;
output += `export const getStatusCounts = (): Record<RoadmapStatus, number> => ({\n`;
output += `  completed: roadmapData.filter((i) => i.status === 'completed').length,\n`;
output += `  'in-progress': roadmapData.filter((i) => i.status === 'in-progress').length,\n`;
output += `  planned: roadmapData.filter((i) => i.status === 'planned').length,\n`;
output += `});\n`;

const outputPath = join(ROOT, 'src', 'data', 'roadmapData.ts');
writeFileSync(outputPath, output, 'utf-8');

// ── Summary ──
const counts = { completed: 0, 'in-progress': 0, planned: 0 };
generated.forEach((i) => counts[i.status]++);

console.log('✅ roadmapData.ts generated successfully!');
console.log(`   ${generated.length} items total: ${counts.completed} completed, ${counts['in-progress']} in-progress, ${counts.planned} planned`);
console.log(`   Output: ${outputPath}`);
