/**
 * Roadmap Data — AUTO-GENERATED by scripts/generateRoadmap.js
 * DO NOT EDIT MANUALLY — edit scripts/roadmap-items.json instead.
 *
 * Run: npm run roadmap
 */

export type RoadmapStatus = 'completed' | 'in-progress' | 'planned';
export type RoadmapCategory = 'feature' | 'ux' | 'community' | 'security';

export interface RoadmapItem {
  id: string;
  title: { it: string; en: string };
  description: { it: string; en: string };
  status: RoadmapStatus;
  category: RoadmapCategory;
  icon: string;
  completedDate?: string;
}

const roadmapData: RoadmapItem[] = [
  /* ──────────── COMPLETED ──────────── */
  {
    id: 'interactive-investment-chart-legends',
    title: { it: 'Grafici investimenti interattivi', en: 'Interactive investment charts' },
    description: {
      it: 'Legenda richiudibile per categoria, selezione di interi gruppi e schede asset con dati societari e dividendi; il pannello Novità ora è progressivo e distingue gli aggiornamenti non letti.',
      en: 'Collapsible category legends, whole-group selection and asset cards with company and dividend data; the What\'s New panel is now progressive and highlights unread updates.'
    },
    status: 'completed',
    category: 'ux',
    icon: '📊',
    completedDate: '2026-07',
  },
  {
    id: 'recurring-transactions',
    title: { it: 'Transazioni Ricorrenti', en: 'Recurring Transactions' },
    description: {
      it: 'Abbonamenti, affitto, stipendio: crea un modello e verrà inserito automaticamente ogni mese, senza bisogno di ricordarsene.',
      en: 'Subscriptions, rent, salary: create a template once and it gets inserted automatically every month, no need to remember.'
    },
    status: 'completed',
    category: 'feature',
    icon: '🔁',
    completedDate: '2026-07',
  },
  {
    id: 'quick-add',
    title: { it: 'Aggiunta Rapida', en: 'Quick Add' },
    description: {
      it: 'Registra un\'uscita o un\'entrata in pochi secondi direttamente dalla dashboard: importo + categoria, il resto è opzionale.',
      en: 'Record an outflow or income in seconds right from the dashboard: amount + category, everything else optional.'
    },
    status: 'completed',
    category: 'ux',
    icon: '⚡',
    completedDate: '2026-07',
  },
  {
    id: 'dashboard-custom',
    title: { it: 'Dashboard Personalizzabile', en: 'Customizable Dashboard' },
    description: {
      it: 'Riordina le sezioni della dashboard trascinandole e scegli tra vista card o tabellare.',
      en: 'Reorder dashboard sections with drag-and-drop and choose between card or table view.'
    },
    status: 'completed',
    category: 'ux',
    icon: '🎨',
    completedDate: '2025-01',
  },
  {
    id: 'gamification',
    title: { it: 'Achievement e Badge', en: 'Achievements & Badges' },
    description: {
      it: '44 badge in 10 categorie per premiare la tua costanza nel tracciamento finanziario.',
      en: '44 badges in 10 categories to reward your consistency in financial tracking.'
    },
    status: 'completed',
    category: 'feature',
    icon: '🏆',
    completedDate: '2025-01',
  },
  {
    id: 'csv-import',
    title: { it: 'Importazione CSV / Excel', en: 'CSV / Excel Import' },
    description: {
      it: 'Importa le tue transazioni da file CSV o Excel con mappatura automatica delle colonne e riconoscimento categorie.',
      en: 'Import your transactions from CSV or Excel files with automatic column mapping and category recognition.'
    },
    status: 'completed',
    category: 'feature',
    icon: '📥',
    completedDate: '2025-02',
  },
  {
    id: 'i18n',
    title: { it: 'Supporto Multilingua', en: 'Multi-Language Support' },
    description: {
      it: 'Interfaccia disponibile in italiano e inglese con rilevamento automatico della lingua.',
      en: 'Interface available in Italian and English with automatic language detection.'
    },
    status: 'completed',
    category: 'ux',
    icon: '🌐',
    completedDate: '2024-12',
  },
  {
    id: 'mobile-nav',
    title: { it: 'Navigazione Mobile Nativa', en: 'Native Mobile Navigation' },
    description: {
      it: 'Navigazione a tab in basso stile app nativa per un\'esperienza mobile fluida.',
      en: 'Bottom tab navigation styled like a native app for a smooth mobile experience.'
    },
    status: 'completed',
    category: 'ux',
    icon: '📱',
    completedDate: '2025-01',
  },
  {
    id: 'anonymous-comparison',
    title: { it: 'Confronto Anonimo', en: 'Anonymous Comparison' },
    description: {
      it: 'Confronta il tuo patrimonio, entrate e uscite con utenti simili in modo completamente anonimo.',
      en: 'Compare your assets, income and outflows with similar users in a completely anonymous way.'
    },
    status: 'completed',
    category: 'feature',
    icon: '📊',
    completedDate: '2024-10',
  },
  {
    id: 'goals-limits',
    title: { it: 'Obiettivi e Limiti di Spesa', en: 'Goals & Spending Limits' },
    description: {
      it: 'Combina soglie fisse e percentuali per spesa, risparmio, investimenti, fondo d\'emergenza e obiettivi personali; monitora anche concentrazione del portafoglio, spese fisse, categorie, debiti e rendita passiva.',
      en: 'Combine fixed and percentage thresholds for spending, savings, investments, emergency funds and personal goals; also track portfolio concentration, fixed expenses, categories, debt and passive income.'
    },
    status: 'completed',
    category: 'feature',
    icon: '🎯',
    completedDate: '2026-07',
  },
  {
    id: 'multi-currency',
    title: { it: 'Supporto Multi-Valuta', en: 'Multi-Currency Support' },
    description: {
      it: 'Visualizza i tuoi dati nella valuta che preferisci (USD, GBP, CHF e altre) con conversione automatica.',
      en: 'View your data in your preferred currency (USD, GBP, CHF and more) with automatic conversion.'
    },
    status: 'completed',
    category: 'feature',
    icon: '💱',
    completedDate: '2025-02',
  },
  {
    id: 'roadmap-feedback',
    title: { it: 'Roadmap e Feedback', en: 'Roadmap & Feedback' },
    description: {
      it: 'Pagina roadmap pubblica e sistema per raccogliere segnalazioni e suggerimenti dalla community.',
      en: 'Public roadmap page and system to collect bug reports and suggestions from the community.'
    },
    status: 'completed',
    category: 'community',
    icon: '🗺️',
    completedDate: '2025-02',
  },
  {
    id: 'trend-charts',
    title: { it: 'Grafici Trend Patrimonio', en: 'Net Worth Trend Charts' },
    description: {
      it: 'Visualizza l\'andamento del tuo patrimonio nel tempo con grafici a linea interattivi.',
      en: 'View your net worth trend over time with interactive line charts.'
    },
    status: 'completed',
    category: 'feature',
    icon: '📈',
    completedDate: '2026-08',
  },
  {
    id: 'stability',
    title: { it: 'App Più Stabile e Affidabile', en: 'More Stable & Reliable App' },
    description: {
      it: 'Risolti problemi di caricamento dopo la registrazione e migliorato il recupero automatico in caso di errori di rete.',
      en: 'Fixed loading issues after registration and improved automatic recovery from network errors.'
    },
    status: 'completed',
    category: 'ux',
    icon: '🛡️',
    completedDate: '2026-02',
  },
  {
    id: 'mobile-ux',
    title: { it: 'Esperienza Mobile Migliorata', en: 'Improved Mobile Experience' },
    description: {
      it: 'Zoom accidentale eliminato, layout ottimizzato e caricamento più veloce su smartphone.',
      en: 'Accidental zoom eliminated, optimized layout and faster loading on smartphones.'
    },
    status: 'completed',
    category: 'ux',
    icon: '📲',
    completedDate: '2026-02',
  },
  {
    id: 'inline-edit',
    title: { it: 'Modifica Inline Transazioni', en: 'Inline Transaction Editing' },
    description: {
      it: 'Modifica entrate e uscite direttamente nella tabella senza uscire dalla vista elenco.',
      en: 'Edit income and outflow entries directly in the table without leaving the list view.'
    },
    status: 'completed',
    category: 'feature',
    icon: '✏️',
    completedDate: '2026-02',
  },
  {
    id: 'pwa-install-guide',
    title: { it: 'Guida Installazione App', en: 'App Install Guide' },
    description: {
      it: 'Istruzioni passo-passo per installare Pacifinance come app, con rilevamento automatico del dispositivo (iOS, Android, Desktop).',
      en: 'Step-by-step instructions to install Pacifinance as an app, with automatic device detection (iOS, Android, Desktop).'
    },
    status: 'completed',
    category: 'ux',
    icon: '📲',
    completedDate: '2026-02',
  },
  {
    id: 'market-prices',
    title: { it: 'Prezzi Crypto in Tempo Reale', en: 'Real-Time Crypto Prices' },
    description: {
      it: 'Monitora i prezzi delle principali criptovalute con grafici sparkline a 7 giorni, direttamente nell\'app.',
      en: 'Monitor major cryptocurrency prices with 7-day sparkline charts, directly in the app.'
    },
    status: 'completed',
    category: 'feature',
    icon: '📈',
    completedDate: '2026-02',
  },
  {
    id: 'account-recovery-code',
    title: { it: 'Recovery Code per il Recupero Account', en: 'Account Recovery Code' },
    description: {
      it: 'Un secondo codice ad alta entropia, separato dalla password, generato alla registrazione (e rigenerabile dalle Impostazioni): un codice a blocchi e una frase di parole equivalenti, con card stampabile e QR, per reimpostare la password senza email e senza la vecchia password.',
      en: 'A separate high-entropy code (not the password), generated at sign-up and regenerable from Settings: an equivalent block code and word phrase, with a printable QR card, to reset your password without email and without the old password.'
    },
    status: 'completed',
    category: 'security',
    icon: '🛟',
    completedDate: '2026-08',
  },
  {
    id: 'multi-insert',
    title: { it: 'Inserimento Multiplo', en: 'Multi-Insert' },
    description: {
      it: 'Inserisci più uscite, entrate o voci di bilancio in un\'unica operazione, risparmiando tempo.',
      en: 'Insert multiple outflows, incomes, or balance entries in a single operation, saving time.'
    },
    status: 'completed',
    category: 'feature',
    icon: '⚡',
    completedDate: '2026-04',
  },
  {
    id: 'detailed-outflow-analysis',
    title: { it: 'Analisi Dettagliata Uscite', en: 'Detailed Outflow Analysis' },
    description: {
      it: 'Analisi approfondita delle uscite per categoria, metodi di pagamento e pattern ricorrenti con confronti mensili.',
      en: 'In-depth outflow analysis by category, payment methods and recurring patterns with monthly comparisons.'
    },
    status: 'completed',
    category: 'feature',
    icon: '📊',
    completedDate: '2026-04',
  },
  {
    id: 'i18n-category-colors',
    title: { it: 'Colori Categorie Multilingua', en: 'Multilingual Category Colors' },
    description: {
      it: 'I colori e le icone delle categorie ora funzionano correttamente in tutte le lingue supportate.',
      en: 'Category colors and icons now work correctly across all supported languages.'
    },
    status: 'completed',
    category: 'ux',
    icon: '🎨',
    completedDate: '2026-04',
  },
  {
    id: 'past-date-balance-choice',
    title: { it: 'Scelta Impatto Bilancio Date Passate', en: 'Past-Date Balance Impact Choice' },
    description: {
      it: 'Quando inserisci spese o entrate con data di un mese passato, puoi scegliere se aggiornare anche il bilancio di quel mese. La scelta è memorizzabile dalle Impostazioni.',
      en: 'When inserting outflows or incomes dated in past months, you can choose whether to update that month\'s balance too. Preference can be saved from Settings.'
    },
    status: 'completed',
    category: 'feature',
    icon: '🕑',
    completedDate: '2026-04',
  },
  {
    id: 'manual-duplicate-check',
    title: { it: 'Controllo Duplicati su Inserimento Manuale', en: 'Duplicate Check on Manual Entry' },
    description: {
      it: 'Aggiungendo una uscita o entrata a mano, l\'app avvisa se una transazione molto simile esiste già nello storico (stessa euristica usata dall\'import CSV), lasciandoti scegliere se salvarla comunque.',
      en: 'When manually adding an outflow or income, the app warns if a very similar transaction already exists in your history (same heuristic used by CSV import), letting you decide whether to save it anyway.'
    },
    status: 'completed',
    category: 'feature',
    icon: '🔍',
    completedDate: '2026-07',
  },
  {
    id: 'shared-expenses',
    title: { it: 'Spese Condivise', en: 'Shared Expenses' },
    description: {
      it: 'Hai pagato per il gruppo (es. un Uber in vacanza)? Segnalo come spesa condivisa: solo la tua quota conta come spesa reale, il resto resta tracciato come credito da recuperare, senza registrare un\'entrata finta quando ti rimborsano.',
      en: 'Paid for the whole group (e.g. an Uber on vacation)? Flag it as a shared expense: only your share counts as real spending, the rest is tracked as a receivable to recover later, with no fake income recorded when you get paid back.'
    },
    status: 'completed',
    category: 'feature',
    icon: '🤝',
    completedDate: '2026-07',
  },
  {
    id: 'live-stock-prices',
    title: { it: 'Prezzi di Mercato Live per Azioni/ETF', en: 'Live Market Prices for Stocks/ETFs' },
    description: {
      it: 'Un pulsante "Aggiorna prezzi" nel pannello holding recupera la quotazione attuale (Finnhub), la converte in EUR e aggiorna il valore corrente — utile soprattutto dopo un import CSV, dove finora era noto solo il costo storico.',
      en: 'A "Refresh prices" button in the holdings panel fetches the current quote (Finnhub), converts it to EUR, and updates the current value — especially useful after a CSV import, where until now only the historical cost basis was known.'
    },
    status: 'completed',
    category: 'feature',
    icon: '📈',
    completedDate: '2026-07',
  },
  {
    id: 'portfolio-insights',
    title: { it: 'Analisi Adattiva del Portafoglio', en: 'Adaptive Portfolio Insights' },
    description: {
      it: 'Guadagno/perdita, posizione migliore/peggiore, media investita al mese e stima del tempo per raggiungere un obiettivo collegato — ogni indicatore si sblocca man mano che inserisci più storico, con suggerimenti chiari su cosa aggiungere per un\'analisi più precisa.',
      en: 'Gain/loss, best/worst position, average monthly contribution, and an ETA estimate toward a linked goal — each figure unlocks as you record more history, with clear hints on what to add for a more precise analysis.'
    },
    status: 'completed',
    category: 'feature',
    icon: '🧭',
    completedDate: '2026-07',
  },
  {
    id: 'investment-monthly-target',
    title: { it: 'Obiettivo di Investimento Mensile', en: 'Monthly Investment Target' },
    description: {
      it: 'Imposta quanto vorresti investire ogni mese e vedi automaticamente, mese per mese, se lo hai raggiunto — direttamente nelle Analisi del Portafoglio, ricostruito dallo storico degli investimenti già registrato.',
      en: 'Set how much you\'d like to invest each month and automatically see, month by month, whether you hit it — right inside Portfolio Insights, reconstructed from the investment history you\'ve already recorded.'
    },
    status: 'completed',
    category: 'feature',
    icon: '🎯',
    completedDate: '2026-07',
  },
  {
    id: 'historical-price-backfill',
    title: { it: 'Recupero Prezzi Storici', en: 'Historical Price Backfill' },
    description: {
      it: 'Un pulsante dedicato recupera un prezzo di mercato mensile per ogni azione/ETF (Finnhub) e crypto (CoinGecko), moltiplicato per la quantità effettivamente posseduta in quel mese — trasforma l\'andamento del portafoglio da una semplice curva di costo storico a un vero andamento di mercato, anche per i mesi precedenti al primo utilizzo di "Aggiorna prezzi".',
      en: 'A dedicated button fetches one monthly market price per stock/ETF (Finnhub) and crypto (CoinGecko), multiplied by the quantity actually held that month — turns the portfolio\'s value-over-time from a plain cost-basis curve into a real market trend, even for months before "Refresh prices" was first used.'
    },
    status: 'completed',
    category: 'feature',
    icon: '🕰️',
    completedDate: '2026-07',
  },
  {
    id: 'community-historical-prices',
    title: { it: 'Prezzi Storici Verificati dalla Community', en: 'Community-Verified Historical Prices' },
    description: {
      it: 'Hai posseduto un titolo o una crypto in un mese passato? Proponi il prezzo che ricordi: resta tuo finché un amministratore non lo verifica confrontandolo con un provider di mercato reale — una volta approvato diventa il prezzo condiviso da tutti gli utenti per quel mese, un\'alternativa gratuita e costruita insieme ai dati storici a pagamento.',
      en: 'Held a stock or crypto in a past month? Submit the price you remember: it stays yours until an admin verifies it against a real market provider — once approved, it becomes the shared price for every user that month, a free, community-built alternative to paid historical data.'
    },
    status: 'completed',
    category: 'feature',
    icon: '🤲',
    completedDate: '2026-07',
  },
  {
    id: 'income-outflow-explorer',
    title: { it: 'Esploratore Entrate e Uscite', en: 'Income and Outflow Explorer' },
    description: {
      it: 'Un\'unica analisi responsive combina KPI, andamento mensile, flusso netto con mesi in deficit, categorie ordinate, confronto con il periodo precedente e tabella esportabile.',
      en: 'One responsive analysis combines KPIs, monthly trends, net cash flow with deficit months, ranked categories, previous-period comparison, and an exportable table.'
    },
    status: 'completed',
    category: 'feature',
    icon: '📊',
    completedDate: '2026-08',
  },
  /* ──────────── IN PROGRESS ──────────── */
  {
    id: 'onboarding',
    title: { it: 'Tour Guidato per Nuovi Utenti', en: 'Guided Tour for New Users' },
    description: {
      it: 'Un tour interattivo che ti guida nella configurazione iniziale e nelle funzionalità principali.',
      en: 'An interactive tour that guides you through initial setup and main features.'
    },
    status: 'in-progress',
    category: 'ux',
    icon: '🚀',
  },
  {
    id: 'feedback-system',
    title: { it: 'Sistema Feedback In-App', en: 'In-App Feedback System' },
    description: {
      it: 'Invia segnalazioni e suggerimenti direttamente dall\'app, creando automaticamente issue su GitHub.',
      en: 'Send bug reports and suggestions directly from the app, automatically creating GitHub issues.'
    },
    status: 'in-progress',
    category: 'community',
    icon: '💬',
  },
  {
    id: 'contribute-section',
    title: { it: 'Sezione Contribuisci', en: 'Contribute Section' },
    description: {
      it: 'Scopri come donare, segnalare bug e proporre nuove idee per migliorare Pacifinance.',
      en: 'Learn how to donate, report bugs, and propose new ideas to improve Pacifinance.'
    },
    status: 'in-progress',
    category: 'community',
    icon: '🤝',
  },
  {
    id: 'roadmap-voting',
    title: { it: 'Voto Priorità Roadmap', en: 'Roadmap Priority Voting' },
    description: {
      it: 'Vota le funzionalità che vuoi vedere per prime e influenza la direzione dello sviluppo.',
      en: 'Vote on features you want to see first and influence the development direction.'
    },
    status: 'in-progress',
    category: 'community',
    icon: '🗳️',
  },
  {
    id: 'auto-detect-bank-format',
    title: { it: 'Riconoscimento Automatico Banca', en: 'Auto-Detect Bank Format' },
    description: {
      it: 'Rilevamento automatico del formato dei file esportati dalla tua banca (Fineco, Intesa, Revolut, N26).',
      en: 'Automatic detection of exported file formats from your bank (Fineco, Intesa, Revolut, N26).'
    },
    status: 'in-progress',
    category: 'feature',
    icon: '🏧',
  },
  {
    id: 'OFX/QIF-support',
    title: { it: 'Supporto File OFX/QIF', en: 'OFX/QIF File Support' },
    description: {
      it: 'Importa le transazioni nel formato standard OFX e QIF usato da molte banche e software finanziari.',
      en: 'Import transactions in standard OFX and QIF format used by many banks and financial software.'
    },
    status: 'in-progress',
    category: 'feature',
    icon: '📂',
  },
  /* ──────────── PLANNED ──────────── */
  {
    id: 'data-export',
    title: { it: 'Esportazione Dati', en: 'Data Export' },
    description: {
      it: 'Esporta i tuoi dati finanziari in formato CSV, Excel, JSON o PDF.',
      en: 'Export your financial data in CSV, Excel, JSON or PDF format.'
    },
    status: 'planned',
    category: 'feature',
    icon: '📤',
  },
  {
    id: 'push-notifications',
    title: { it: 'Promemoria Mensili', en: 'Monthly Reminders' },
    description: {
      it: 'Ricevi un promemoria quando è il momento di aggiornare i tuoi dati finanziari.',
      en: 'Get a reminder when it\'s time to update your financial data.'
    },
    status: 'planned',
    category: 'feature',
    icon: '🔔',
  },
  {
    id: 'bank-templates',
    title: { it: 'Template Bancari per Import', en: 'Bank Import Templates' },
    description: {
      it: 'Importa i dati dalla tua banca con template preconfigurati (Fineco, Revolut, N26 e altri).',
      en: 'Import data from your bank with pre-configured templates (Fineco, Revolut, N26 and more).'
    },
    status: 'planned',
    category: 'feature',
    icon: '🏦',
  },
  {
    id: 'pdf-reports',
    title: { it: 'Report PDF Avanzati', en: 'Advanced PDF Reports' },
    description: {
      it: 'Report PDF completi con grafici, tabelle e analisi dettagliate del tuo patrimonio.',
      en: 'Complete PDF reports with charts, tables and detailed analysis of your assets.'
    },
    status: 'planned',
    category: 'feature',
    icon: '📄',
  },
  {
    id: 'more-languages',
    title: { it: 'Più Lingue Supportate', en: 'More Supported Languages' },
    description: {
      it: 'Supporto per spagnolo, francese, tedesco, portoghese e altre lingue.',
      en: 'Support for Spanish, French, German, Portuguese and more languages.'
    },
    status: 'planned',
    category: 'ux',
    icon: '🗣️',
  },
  {
    id: 'budget-planner',
    title: { it: 'Pianificatore di Budget', en: 'Budget Planner' },
    description: {
      it: 'Pianifica il tuo budget mensile con scenari "what if" e simulazioni.',
      en: 'Plan your monthly budget with "what if" scenarios and simulations.'
    },
    status: 'planned',
    category: 'feature',
    icon: '💰',
  },
  {
    id: '2fa',
    title: { it: 'Autenticazione a Due Fattori', en: 'Two-Factor Authentication' },
    description: {
      it: 'Proteggi il tuo account con un secondo livello di sicurezza.',
      en: 'Protect your account with a second layer of security.'
    },
    status: 'planned',
    category: 'security',
    icon: '🔐',
  },
];

export default roadmapData;

/**
 * Get items filtered by status
 */
export const getItemsByStatus = (status: RoadmapStatus): RoadmapItem[] =>
  roadmapData.filter((item) => item.status === status);

/**
 * Get count of items per status
 */
export const getStatusCounts = (): Record<RoadmapStatus, number> => ({
  completed: roadmapData.filter((i) => i.status === 'completed').length,
  'in-progress': roadmapData.filter((i) => i.status === 'in-progress').length,
  planned: roadmapData.filter((i) => i.status === 'planned').length,
});
